export const photoMap: Record<string, any> = {
  'the-beatherder-stage': require('@/assets/images/stages/photo/the-beatherder-stage.jpg'),
  'toil-trees': require('@/assets/images/stages/photo/toil-trees.jpg'),
  'the-fortress': require('@/assets/images/stages/photo/the-fortress.jpg'),
  'the-ring': require('@/assets/images/stages/photo/the-ring.jpg'),
  'stumblefunk-factory': require('@/assets/images/stages/photo/stumblefunk-factory.jpg'),
  'working-mens-club': require('@/assets/images/stages/photo/working-mens-club.jpg'),
  'smoky-tentacles': require('@/assets/images/stages/photo/smoky-tentacles.jpg'),
  'bushrocker-hi-fi': require('@/assets/images/stages/photo/bushrocker-hi-fi.jpg'),
  'the-snug': require('@/assets/images/stages/photo/the-snug.jpg'),
  'the-parish-church': require('@/assets/images/stages/photo/the-parish-church.jpg'),
  'sunrise': require('@/assets/images/stages/photo/sunrise.jpg'),
  'bubba-gumma': require('@/assets/images/stages/photo/bubba-gumma.jpg'),
  'launderette': require('@/assets/images/stages/photo/launderette.jpg'),
  'the-garage': require('@/assets/images/stages/photo/the-garage.jpg'),
  'julies-barn': require('@/assets/images/stages/photo/julies-barn.jpg'),
  'hotel-california': require('@/assets/images/stages/photo/hotel-california.jpg'),
};

export const logoMap: Record<string, any> = {
  'the-beatherder-stage': require('@/assets/images/stages/logo/the-beatherder-stage.png'),
  'toil-trees': require('@/assets/images/stages/logo/toil-trees.png'),
  'the-fortress': require('@/assets/images/stages/logo/the-fortress.png'),
  'the-ring': require('@/assets/images/stages/logo/the-ring.png'),
  'stumblefunk-factory': require('@/assets/images/stages/logo/stumblefunk-factory.png'),
  'working-mens-club': require('@/assets/images/stages/logo/working-mens-club.png'),
  'smoky-tentacles': require('@/assets/images/stages/logo/smoky-tentacles.png'),
  'bushrocker-hi-fi': require('@/assets/images/stages/logo/bushrocker-hi-fi.png'),
  'the-snug': require('@/assets/images/stages/logo/the-snug.png'),
  'the-parish-church': require('@/assets/images/stages/logo/the-parish-church.png'),
  'sunrise': require('@/assets/images/stages/logo/sunrise.png'),
  'bubba-gumma': require('@/assets/images/stages/logo/bubba-gumma.png'),
  'launderette': require('@/assets/images/stages/logo/launderette.png'),
  'the-garage': require('@/assets/images/stages/logo/the-garage.png'),
  'julies-barn': require('@/assets/images/stages/logo/julies-barn.png'),
  'hotel-california': require('@/assets/images/stages/logo/hotel-california.png'),
};
